import type { Metadata } from "next";
import OnboardingNav from "@/components/onboarding-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col gap-4 space-y-10 max-h-screen">
      <OnboardingNav />
      <div className="max-w-md mx-auto">{children}</div>
    </div>
  );
}
